import type { RevolverApi } from "../shared/types";
import { createWebApi } from "./webApi";

export type {
  CatalogModel,
  ChatConversation,
  ChatMessage,
  ConversationDetail,
  ConversationMeta,
  CreateServerRequest,
  EngineConfigField,
  EngineId,
  EngineInfo,
  GpuInfo,
  GpuDevice,
  GpuVendor,
  GpuMode,
  ServerRuntimeMode,
  HubModel,
  InferenceBackend,
  LocalGgufModel,
  LoadProgress,
  LoadedModelState,
  LocalPaths,
  LocalSettings,
  MonitorSnapshot,
  PlatformCapabilities,
  RevolverConfig,
  RuntimeConfig,
  ServerConfig,
  ServerDefinition,
  ServerInstanceStatus,
  ServerLoadPhase,
  ServerStatus,
  SendMessageOptions,
  StreamDelta,
  SystemInfo,
  VramEstimate,
  BenchmarkCategory,
  BenchmarkCheckResult,
  BenchmarkDefinition,
  BenchmarkRun,
  BenchmarkTestResult,
  StartBenchmarkRequest,
  RevolverSettingsView,
  SettingsPatch,
  HubModelSearchResult,
  HubRepoFile,
  HubFormatFilter,
  HubSearchSort,
  DownloadJob,
  StartModelDownloadRequest,
  RuntimeId,
  RuntimeInstallJob,
  RuntimeStatus,
} from "../shared/types";

export const api: RevolverApi =
  typeof window !== "undefined" && window.revolver ? window.revolver : createWebApi();
